### PR TITLE
Accessible control

### LINKED ISSUE #19: [accessibility] `title` does not label the control
control-not-accessible

The `title` should be set on the `<a>` control instead of the parent `<div>`. This ensures users with screen readers can access the `title` description.

### LINKED ISSUE #20: [accessibility] Control should have `role="button"`
The control is conveyed as <q>link</q> to screen reader users, the control should be `role="button"` ([same as Leaflet controls](https://github.com/Leaflet/Leaflet/blob/bc918d4bdc2ba189807bc207c77080fb41ecc196/src/control/Control.Zoom.js#L91)).

### PR DESCRIPTION
**Pull request by Malvoz**
- https://github.com/consbio/Leaflet.ZoomBox/commit/3e33aee5ae307485c6b96e82f299935a96dfb7fc ensures the `title` is available to <span title="Assistive Technology">ATs</span> (closes https://github.com/consbio/Leaflet.ZoomBox/issues/19)
- https://github.com/consbio/Leaflet.ZoomBox/commit/14486e41007e04e5cb58fb50d88bdb0469f5b07e conveys that the control is a button using [`role="button"`](https://www.w3.org/TR/wai-aria-1.2/#button) (closes https://github.com/consbio/Leaflet.ZoomBox/issues/20)
- https://github.com/consbio/Leaflet.ZoomBox/commit/a95e6fd456c25583b86f140fb56423f102b81c60 conveys the pressed state using [`aria-pressed`](https://www.w3.org/TR/wai-aria-1.2/#aria-pressed)
- https://github.com/consbio/Leaflet.ZoomBox/commit/8fca3a930054786cbac42c2b3564122f995eb0d8 conveys the disabled state using [`aria-disabled`](https://www.w3.org/TR/wai-aria-1.2/#aria-disabled)

### CODE REVIEW

**Review by brendan-ward — APPROVED** [review]
Thanks @Malvoz !

**Comment by Malvoz** [comment]
I was considering bumping the version in package.json on my end, but I'm not sure that's proper Github etiquette. 😋

**Comment by brendan-ward** [comment]
Usually package maintainers like to be in charge of versions, but I imagine that varies project to project.

I'm updating version now (0.5.2) and preparing to publish to NPM...

**Comment by brendan-ward** [comment]
On NPM now: https://www.npmjs.com/package/leaflet-zoombox

Thanks again for adding this!

**Pull request merged**
